#ifndef UTIL_CUSTOMQTMETATYPES_H
#define UTIL_CUSTOMQTMETATYPES_H

#include <QMetaType>
#include <portaudio.h>

Q_DECLARE_METATYPE(PaDeviceIndex)
Q_DECLARE_METATYPE(uint64_t)
Q_DECLARE_METATYPE(int16_t)

#endif // UTIL_CUSTOMQTMETATYPES_H
